### ISSUE TITLE
JSON Client-Server Communication

### ISSUE THREAD

**Issue by ethragur** [ethragur/SMRTMS#14]
Acceptance:

Implement a simple program which sends Information between a server and client. 

2hrs

**Comment by ethragur** [comment]
JSON Reader and Writer implemented on Clientside via GSON.

Tutorial for ServerClient Communication: http://osamashabrez.com/client-server-communication-android-json/ @HunterwolfAT  @mike7549  @ethragur

**Comment by HunterwolfAT** [comment]
Ah, Danke!

**Comment by ethragur** [comment]
Really Important, switch to Websocket

**Comment by ethragur** [comment]
Client and Server already implemented by me, Will push later because I have to compile it first

**Comment by ethragur** [comment]
Will push example to my Github ServerClientTest

**Comment by HunterwolfAT** [comment]
Des müss ma uns es nächste mal besser absprechen, damit i nit wieder arbeit umsonst mach. Wenn i glei websockets hernemmen hab sollen, dann hättest du nit den link oben posten dürfen, weil i hab des jetzt halt so angfangen wie in dem link beschrieben.

**Comment by ethragur** [comment]
aso. hast du schon damit begonnen?

**Comment by HunterwolfAT** [comment]
Joah, siehe Commits, war eh no nit viel, aber trotzem fast a stunde eini lesen und umma probiern

**Comment by ethragur** [comment]
Ok sry, nächstes mal werd i davor schreiben.

Hab im phil schu gsagt das er uns in port 8887 auf seinem server freischalten soll. Auf client side is er schu implementiert. Zum recieven werden wir halt doch no irgendeinen Listener brauchen

**Comment by HunterwolfAT** [comment]
Works pretty well now I'd say!
