### ISSUE TITLE
Better Communication between Client and Server

### ISSUE THREAD

**Issue by ethragur** [ethragur/SMRTMS#25]
Acceptance:

Design system where JSON files are send over the server
UserData, Friend lists, Authentication Tokens, Events . . .

Server must read JSON file and react accordingly
Implement JSON Reader & Writer on Client and Server
Write Useful Unit Tests /s
 
@HunterwolfAT 
@mike7549

**Comment by ethragur** [comment]
Send json Files

**Comment by HunterwolfAT** [comment]
Json Files are being read and written by Client and Server succesfully now. Logic of what to do with them is still missing, however
