### ISSUE TITLE
Server implementation planning

### ISSUE THREAD

**Issue by HunterwolfAT** [ethragur/SMRTMS#8]
The server needs to process data and therefore can not just be a mySQL database running somewhere.
What does the server software need to do? 
How will the communication between server and client work?
The server should work fully automatic, no input from an admin required... right?

3 Hours

**Comment by HunterwolfAT** [comment]
## What does the server do?
We still need to discuss this in more detail, but as far as I understood it:
* Keeps track of user settings and data, including
     * Name, personal details
     * Friends list, including grouping those friends
* Calculates averages of ratings
* Authentication (unless we use a third party API for that)
Please, everybody who likes to add to this list via a comment is welcome to.

What it does not do:
* Handling the chat function. The chat plugin we use is peer-to-peer
* Keep track of geographic data. That is stored in the database.
* Constantly send data to the client. The client queries the database, while the server monitors and manipulates the data in the server.
* Authenticate. Again, maybe, depends how we implement it

However, there is an important difference between the server __computer__ and the server __application__.
## Server Computer
The machine that functions as the server of our application. On it runs
* A SQL server software
* Our Java-based server software

Ideally, starting our server software automatically calls the sql server to start as well.

## Server Software
For the above mentioned functions, we can write a stand-alone Java application that connects to the SQL database and monitors it.

When the server gets notified that a change has occurred, it fetches the relevant data from the database, does the necessary calculations, and returns the results back into the database.

How this message system can be implemented is up for debate.

**Comment by HunterwolfAT** [comment]
### Things the server could do to justify it's existence better
* Generate events or data on regular intervals without user input
* Push notifications or alarms to users
* Calculate statistics (User statistics, Most popular events or bars)

Possible use cases:
* Notify user that desired bar has high attendance (and could be full) - maybe choose a different one? Or maybe that is just more reason to go there.
* Notify user that many of her friends are meeting up somewhere else - maybe join?
* Suggest friends with whom has not been spend as much time

**Comment by ethragur** [comment]
Database Server: www.jooq.org einfacher Java Server.

**Comment by ethragur** [comment]
http://osamashabrez.com/client-server-communication-android-json/
